#!/bin/sh
set -e

LEASE_FILE=/tmp/dhcp.leases
BACKUP_TABLE=/etc/iptmon_backup.ipt
TABLE=$(mktemp -p /tmp -u iptmon_XXXXXX)

CHAIN_FW_TX="iptmon_tx"
CHAIN_FW_RX="iptmon_rx"
CHAIN_INPUT="iptmon_input"
CHAIN_OUTPUT="iptmon_output"

usage() {
  echo "$0 [init|update|remove]"
}

remove() {
	echo "-D $CHAIN_INPUT"
	echo "-D $CHAIN_OUTPUT"
	echo "-D $CHAIN_FWD"
}

# dhcp.leases format, hostname in 4th column
add_rule() {
  echo "-A $CHAIN_FW_TX -s $4 -j RETURN -m comment --comment \"tx_$4\""
  echo "-A $CHAIN_FW_RX -d $4 -j RETURN -m comment --comment \"rx_$4\""
}

commit() {
	echo "COMMIT" >> $TABLE
	iptables-restore -T mangle < $TABLE
}

update_chain() {
	while read -r line; do
		add_rule $line
	done < $1 >> $TABLE
}

backup_orig() {
	test -f $BACKUP_TABLE || iptables-save -t mangle > $1
}

restore_orig() {
	iptables-restore -T mangle < $1
	rm -f $1
}

init_chain() {
 cat <<-EOF >> $TABLE
		*mangle
		:PREROUTING ACCEPT
		:INPUT ACCEPT
		:FORWARD ACCEPT
		:OUTPUT ACCEPT
		:POSTROUTING ACCEPT
		:$CHAIN_FW_TX - [0:0]
		:$CHAIN_FW_RX - [0:0]
		:$CHAIN_INPUT - [0:0]
		:$CHAIN_OUTPUT - [0:0]
		-A INPUT -j $CHAIN_INPUT
		-A FORWARD -j $CHAIN_FW_TX
		-A FORWARD -j $CHAIN_FW_RX
		-A OUTPUT -j $CHAIN_OUTPUT
		-F $CHAIN_FW_TX
		-F $CHAIN_FW_RX
	EOF
}

finalize_chain() {
	cat <<-EOF >> $TABLE
		-A $CHAIN_INPUT -j RETURN
		-A $CHAIN_OUTPUT -j RETURN
	EOF
}

_cleanup() {
	rm -f $TABLE
}

test "$(id -u)" -eq 0 || { echo "must be root"; exit 1; }
trap _cleanup EXIT

case $1 in
	"init")
		backup_orig $BACKUP_TABLE
		init_chain
		update_chain $LEASE_FILE
		finalize_chain
		commit
	;;
	"update")
		init_chain
		update_chain $LEASE_FILE
		finalize_chain
		commit
	;;
	"remove")
		restore_orig $BACKUP_TABLE
	;;
 *)
	usage
	;;
esac